from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx2

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.roblox_two_step_verification_api_regenerate_recovery_codes_request import (
    RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest,
)
from ...models.roblox_two_step_verification_api_regenerate_recovery_codes_response import (
    RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse,
)
from ...types import UNSET, Response, Unset


def _get_kwargs(
    user_id: int,
    *,
    body: RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "https://twostepverification.roblox.com/v1/users/{user_id}/recovery-codes/regenerate".format(
            user_id=quote(str(user_id), safe=""),
        ),
        "extensions": {
            "openapi-extensions": {"x-roblox-engine-usability": {"apiKeyWithHttpService": False}},
            "openapi-id": "post_v1_users_userId_recovery-codes_regenerate",
        },
    }

    if isinstance(body, RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest):
        _kwargs["json"] = body.to_dict()

        headers["Content-Type"] = "application/json"
    if isinstance(body, RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest):
        _kwargs["json"] = body.to_dict()

        headers["Content-Type"] = "text/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx2.Response
) -> Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse | None:
    if response.status_code == 200:
        response_200 = RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = cast(Any, None)
        return response_400

    if response.status_code == 401:
        response_401 = cast(Any, None)
        return response_401

    if response.status_code == 403:
        response_403 = cast(Any, None)
        return response_403

    if response.status_code == 429:
        response_429 = cast(Any, None)
        return response_429

    if response.status_code == 503:
        response_503 = cast(Any, None)
        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx2.Response
) -> Response[Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    user_id: int,
    *,
    client: AuthenticatedClient,
    body: RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | Unset = UNSET,
) -> Response[Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse]:
    """Clears any existing recovery codes and generates a new batch of recovery codes.

     Two step verification recovery codes do not enforce that two step verification must be passed when
    logging in.
    At least one two step verification media type must be enabled to trigger the two step verification
    flow.
    Recovery codes are intended to be used to pass two step verification when the enabled media type is
    unavailable.

    Recovery codes generated by this endpoint do not have an expiration.

    Once a recovery code generated by this endpoint has been used it cannot be used again.

    Args:
        user_id (int):
        body (RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest): Request information
            needed to regenerate recovery codes.
        body (RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest): Request information
            needed to regenerate recovery codes.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse]
    """

    kwargs = _get_kwargs(
        user_id=user_id,
        body=body,
    )

    response = client.get_httpx2_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    user_id: int,
    *,
    client: AuthenticatedClient,
    body: RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | Unset = UNSET,
) -> Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse | None:
    """Clears any existing recovery codes and generates a new batch of recovery codes.

     Two step verification recovery codes do not enforce that two step verification must be passed when
    logging in.
    At least one two step verification media type must be enabled to trigger the two step verification
    flow.
    Recovery codes are intended to be used to pass two step verification when the enabled media type is
    unavailable.

    Recovery codes generated by this endpoint do not have an expiration.

    Once a recovery code generated by this endpoint has been used it cannot be used again.

    Args:
        user_id (int):
        body (RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest): Request information
            needed to regenerate recovery codes.
        body (RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest): Request information
            needed to regenerate recovery codes.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse
    """

    return sync_detailed(
        user_id=user_id,
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    user_id: int,
    *,
    client: AuthenticatedClient,
    body: RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | Unset = UNSET,
) -> Response[Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse]:
    """Clears any existing recovery codes and generates a new batch of recovery codes.

     Two step verification recovery codes do not enforce that two step verification must be passed when
    logging in.
    At least one two step verification media type must be enabled to trigger the two step verification
    flow.
    Recovery codes are intended to be used to pass two step verification when the enabled media type is
    unavailable.

    Recovery codes generated by this endpoint do not have an expiration.

    Once a recovery code generated by this endpoint has been used it cannot be used again.

    Args:
        user_id (int):
        body (RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest): Request information
            needed to regenerate recovery codes.
        body (RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest): Request information
            needed to regenerate recovery codes.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse]
    """

    kwargs = _get_kwargs(
        user_id=user_id,
        body=body,
    )

    response = await client.get_async_httpx2_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    user_id: int,
    *,
    client: AuthenticatedClient,
    body: RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest
    | Unset = UNSET,
) -> Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse | None:
    """Clears any existing recovery codes and generates a new batch of recovery codes.

     Two step verification recovery codes do not enforce that two step verification must be passed when
    logging in.
    At least one two step verification media type must be enabled to trigger the two step verification
    flow.
    Recovery codes are intended to be used to pass two step verification when the enabled media type is
    unavailable.

    Recovery codes generated by this endpoint do not have an expiration.

    Once a recovery code generated by this endpoint has been used it cannot be used again.

    Args:
        user_id (int):
        body (RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest): Request information
            needed to regenerate recovery codes.
        body (RobloxTwoStepVerificationApiRegenerateRecoveryCodesRequest): Request information
            needed to regenerate recovery codes.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | RobloxTwoStepVerificationApiRegenerateRecoveryCodesResponse
    """

    return (
        await asyncio_detailed(
            user_id=user_id,
            client=client,
            body=body,
        )
    ).parsed
