project_name_override: roblox-open-cloud-openapi
package_name_override: roblox_open_cloud_openapi

package_version_override: 0.1.0

post_hooks:
  - "ruff check --fix-only ./roblox_open_cloud_openapi"
  - "ruff format ./roblox_open_cloud_openapi"

content_type_overrides:
  text/json: application/json
