from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx2

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.cloud_list_luau_execution_session_task_logs_view import CloudListLuauExecutionSessionTaskLogsView
from ...models.list_luau_execution_session_task_logs_response import ListLuauExecutionSessionTaskLogsResponse
from ...types import UNSET, Response, Unset


def _get_kwargs(
    universe_id: str,
    place_id: str,
    version_id: str,
    luau_execution_session_id: str,
    task_id: str,
    *,
    max_page_size: int | Unset = UNSET,
    page_token: str | Unset = UNSET,
    view: CloudListLuauExecutionSessionTaskLogsView | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["maxPageSize"] = max_page_size

    params["pageToken"] = page_token

    json_view: str | Unset = UNSET
    if not isinstance(view, Unset):
        json_view = view.value

    params["view"] = json_view

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/cloud/v2/universes/{universe_id}/places/{place_id}/versions/{version_id}/luau-execution-sessions/{luau_execution_session_id}/tasks/{task_id}/logs".format(
            universe_id=quote(str(universe_id), safe=""),
            place_id=quote(str(place_id), safe=""),
            version_id=quote(str(version_id), safe=""),
            luau_execution_session_id=quote(str(luau_execution_session_id), safe=""),
            task_id=quote(str(task_id), safe=""),
        ),
        "params": params,
        "openapi-extensions": {
            "x-roblox-engine-usability": {"apiKeyWithHttpService": True},
            "x-roblox-scopes": [
                {"name": "universe.place.luau-execution-session:read"},
                {"name": "universe.place.luau-execution-session:write"},
            ],
            "x-roblox-docs": {
                "category": "Luau execution",
                "methodProperties": {
                    "scopes": [
                        "universe.place.luau-execution-session:read",
                        "universe.place.luau-execution-session:write",
                    ]
                },
                "resource": {
                    "$ref": "#/components/schemas/LuauExecutionSessionTaskLog",
                    "name": "LuauExecutionSessionTaskLog",
                },
            },
            "x-roblox-stability": "STABLE",
            "x-roblox-rate-limits": {"perApiKeyOwner": {"period": "MINUTE", "maxInPeriod": 45}},
        },
        "openapi-id": "Cloud_ListLuauExecutionSessionTaskLogs",
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx2.Response
) -> ListLuauExecutionSessionTaskLogsResponse | None:
    if response.status_code == 200:
        response_200 = ListLuauExecutionSessionTaskLogsResponse.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx2.Response
) -> Response[ListLuauExecutionSessionTaskLogsResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    universe_id: str,
    place_id: str,
    version_id: str,
    luau_execution_session_id: str,
    task_id: str,
    *,
    client: AuthenticatedClient,
    max_page_size: int | Unset = UNSET,
    page_token: str | Unset = UNSET,
    view: CloudListLuauExecutionSessionTaskLogsView | Unset = UNSET,
) -> Response[ListLuauExecutionSessionTaskLogsResponse]:
    """List Luau Execution Session Task Logs

     Lists log chunks generated by a `LuauExecutionSessionTask`.

    Quotas:
    * 45 calls per minute per API key owner or IP address

    Args:
        universe_id (str):
        place_id (str):
        version_id (str):
        luau_execution_session_id (str):
        task_id (str):
        max_page_size (int | Unset):
        page_token (str | Unset):
        view (CloudListLuauExecutionSessionTaskLogsView | Unset):  Example: VIEW_UNSPECIFIED.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ListLuauExecutionSessionTaskLogsResponse]
    """

    kwargs = _get_kwargs(
        universe_id=universe_id,
        place_id=place_id,
        version_id=version_id,
        luau_execution_session_id=luau_execution_session_id,
        task_id=task_id,
        max_page_size=max_page_size,
        page_token=page_token,
        view=view,
    )

    response = client.get_httpx2_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    universe_id: str,
    place_id: str,
    version_id: str,
    luau_execution_session_id: str,
    task_id: str,
    *,
    client: AuthenticatedClient,
    max_page_size: int | Unset = UNSET,
    page_token: str | Unset = UNSET,
    view: CloudListLuauExecutionSessionTaskLogsView | Unset = UNSET,
) -> ListLuauExecutionSessionTaskLogsResponse | None:
    """List Luau Execution Session Task Logs

     Lists log chunks generated by a `LuauExecutionSessionTask`.

    Quotas:
    * 45 calls per minute per API key owner or IP address

    Args:
        universe_id (str):
        place_id (str):
        version_id (str):
        luau_execution_session_id (str):
        task_id (str):
        max_page_size (int | Unset):
        page_token (str | Unset):
        view (CloudListLuauExecutionSessionTaskLogsView | Unset):  Example: VIEW_UNSPECIFIED.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ListLuauExecutionSessionTaskLogsResponse
    """

    return sync_detailed(
        universe_id=universe_id,
        place_id=place_id,
        version_id=version_id,
        luau_execution_session_id=luau_execution_session_id,
        task_id=task_id,
        client=client,
        max_page_size=max_page_size,
        page_token=page_token,
        view=view,
    ).parsed


async def asyncio_detailed(
    universe_id: str,
    place_id: str,
    version_id: str,
    luau_execution_session_id: str,
    task_id: str,
    *,
    client: AuthenticatedClient,
    max_page_size: int | Unset = UNSET,
    page_token: str | Unset = UNSET,
    view: CloudListLuauExecutionSessionTaskLogsView | Unset = UNSET,
) -> Response[ListLuauExecutionSessionTaskLogsResponse]:
    """List Luau Execution Session Task Logs

     Lists log chunks generated by a `LuauExecutionSessionTask`.

    Quotas:
    * 45 calls per minute per API key owner or IP address

    Args:
        universe_id (str):
        place_id (str):
        version_id (str):
        luau_execution_session_id (str):
        task_id (str):
        max_page_size (int | Unset):
        page_token (str | Unset):
        view (CloudListLuauExecutionSessionTaskLogsView | Unset):  Example: VIEW_UNSPECIFIED.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ListLuauExecutionSessionTaskLogsResponse]
    """

    kwargs = _get_kwargs(
        universe_id=universe_id,
        place_id=place_id,
        version_id=version_id,
        luau_execution_session_id=luau_execution_session_id,
        task_id=task_id,
        max_page_size=max_page_size,
        page_token=page_token,
        view=view,
    )

    response = await client.get_async_httpx2_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    universe_id: str,
    place_id: str,
    version_id: str,
    luau_execution_session_id: str,
    task_id: str,
    *,
    client: AuthenticatedClient,
    max_page_size: int | Unset = UNSET,
    page_token: str | Unset = UNSET,
    view: CloudListLuauExecutionSessionTaskLogsView | Unset = UNSET,
) -> ListLuauExecutionSessionTaskLogsResponse | None:
    """List Luau Execution Session Task Logs

     Lists log chunks generated by a `LuauExecutionSessionTask`.

    Quotas:
    * 45 calls per minute per API key owner or IP address

    Args:
        universe_id (str):
        place_id (str):
        version_id (str):
        luau_execution_session_id (str):
        task_id (str):
        max_page_size (int | Unset):
        page_token (str | Unset):
        view (CloudListLuauExecutionSessionTaskLogsView | Unset):  Example: VIEW_UNSPECIFIED.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ListLuauExecutionSessionTaskLogsResponse
    """

    return (
        await asyncio_detailed(
            universe_id=universe_id,
            place_id=place_id,
            version_id=version_id,
            luau_execution_session_id=luau_execution_session_id,
            task_id=task_id,
            client=client,
            max_page_size=max_page_size,
            page_token=page_token,
            view=view,
        )
    ).parsed
