from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.luau_execution_session_task import LuauExecutionSessionTask
from ...types import Response


def _get_kwargs(
    universe_id: str,
    place_id: str,
    *,
    body: LuauExecutionSessionTask,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/cloud/v2/universes/{universe_id}/places/{place_id}/luau-execution-session-tasks".format(
            universe_id=quote(str(universe_id), safe=""),
            place_id=quote(str(place_id), safe=""),
        ),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> LuauExecutionSessionTask | None:
    if response.status_code == 200:
        response_200 = LuauExecutionSessionTask.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[LuauExecutionSessionTask]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    universe_id: str,
    place_id: str,
    *,
    client: AuthenticatedClient,
    body: LuauExecutionSessionTask,
) -> Response[LuauExecutionSessionTask]:
    """Create Luau Execution Session Task

     Creates a task but does not wait for the task to complete.

    To check whether a task has
    completed, call the `GetLuauExecutionSessionTask` method and inspect the
    `state` field of the returned resource.

    Quotas:
    * 5 calls per minute per API key owner
    * 45 calls per minute per IP address

    Args:
        universe_id (str):
        place_id (str):
        body (LuauExecutionSessionTask): A `LuauExecutionSessionTask` ("task" for short) executes
            a given Luau script
            in the context of a specific version of a place.

            In a task, physics simulation does not run. Server and local scripts within
            the place also do not automatically run.

            The script may access and update the data model of the place, including
            invoking any module scripts. However, data model changes are local to the
            task and cannot be persisted.

            The script can also invoke engine APIs that read and/or modify data stored in
            the cloud, such as those for DataStores. Exercise caution when using these
            APIs.

            Scripts can be up to 4 MB in size and run for up to 5 minutes. Scripts that
            run for longer than the time limit terminate with an error.

            Scripts are executed as-is and do not need to be wrapped in a function.

            Scripts can return values (using the Luau `return` keyword). Return values
            are serialized to JSON and can be retrieved with the `Get
            LuauExecutionSessionTask` API after the task completes. The total size of the
            return values after JSON serialization must not exceed 4 MB. If the limit is
            exceeded, the task terminates with an error.

            If the script raises an unhandled error, the task terminates. The error
            information can be retrieved with the `GetLuauExecutionSessionTask` API.

            Standard output (generated by the Luau `print` function) can be retrieved
            with the `ListLuauExecutionSessionTaskLogs` method after the task completes.
            A maximum of 450 KB of logs are retained. If the amount of logs exceeds the
            limit, older logs are discarded.

            Information about a task is retained for 24 hours after task completion.

            At most ten incomplete tasks are allowed per place. Attempting to create more
            tasks while the first ten are incomplete results in a HTTP 429 response.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[LuauExecutionSessionTask]
    """

    kwargs = _get_kwargs(
        universe_id=universe_id,
        place_id=place_id,
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    universe_id: str,
    place_id: str,
    *,
    client: AuthenticatedClient,
    body: LuauExecutionSessionTask,
) -> LuauExecutionSessionTask | None:
    """Create Luau Execution Session Task

     Creates a task but does not wait for the task to complete.

    To check whether a task has
    completed, call the `GetLuauExecutionSessionTask` method and inspect the
    `state` field of the returned resource.

    Quotas:
    * 5 calls per minute per API key owner
    * 45 calls per minute per IP address

    Args:
        universe_id (str):
        place_id (str):
        body (LuauExecutionSessionTask): A `LuauExecutionSessionTask` ("task" for short) executes
            a given Luau script
            in the context of a specific version of a place.

            In a task, physics simulation does not run. Server and local scripts within
            the place also do not automatically run.

            The script may access and update the data model of the place, including
            invoking any module scripts. However, data model changes are local to the
            task and cannot be persisted.

            The script can also invoke engine APIs that read and/or modify data stored in
            the cloud, such as those for DataStores. Exercise caution when using these
            APIs.

            Scripts can be up to 4 MB in size and run for up to 5 minutes. Scripts that
            run for longer than the time limit terminate with an error.

            Scripts are executed as-is and do not need to be wrapped in a function.

            Scripts can return values (using the Luau `return` keyword). Return values
            are serialized to JSON and can be retrieved with the `Get
            LuauExecutionSessionTask` API after the task completes. The total size of the
            return values after JSON serialization must not exceed 4 MB. If the limit is
            exceeded, the task terminates with an error.

            If the script raises an unhandled error, the task terminates. The error
            information can be retrieved with the `GetLuauExecutionSessionTask` API.

            Standard output (generated by the Luau `print` function) can be retrieved
            with the `ListLuauExecutionSessionTaskLogs` method after the task completes.
            A maximum of 450 KB of logs are retained. If the amount of logs exceeds the
            limit, older logs are discarded.

            Information about a task is retained for 24 hours after task completion.

            At most ten incomplete tasks are allowed per place. Attempting to create more
            tasks while the first ten are incomplete results in a HTTP 429 response.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        LuauExecutionSessionTask
    """

    return sync_detailed(
        universe_id=universe_id,
        place_id=place_id,
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    universe_id: str,
    place_id: str,
    *,
    client: AuthenticatedClient,
    body: LuauExecutionSessionTask,
) -> Response[LuauExecutionSessionTask]:
    """Create Luau Execution Session Task

     Creates a task but does not wait for the task to complete.

    To check whether a task has
    completed, call the `GetLuauExecutionSessionTask` method and inspect the
    `state` field of the returned resource.

    Quotas:
    * 5 calls per minute per API key owner
    * 45 calls per minute per IP address

    Args:
        universe_id (str):
        place_id (str):
        body (LuauExecutionSessionTask): A `LuauExecutionSessionTask` ("task" for short) executes
            a given Luau script
            in the context of a specific version of a place.

            In a task, physics simulation does not run. Server and local scripts within
            the place also do not automatically run.

            The script may access and update the data model of the place, including
            invoking any module scripts. However, data model changes are local to the
            task and cannot be persisted.

            The script can also invoke engine APIs that read and/or modify data stored in
            the cloud, such as those for DataStores. Exercise caution when using these
            APIs.

            Scripts can be up to 4 MB in size and run for up to 5 minutes. Scripts that
            run for longer than the time limit terminate with an error.

            Scripts are executed as-is and do not need to be wrapped in a function.

            Scripts can return values (using the Luau `return` keyword). Return values
            are serialized to JSON and can be retrieved with the `Get
            LuauExecutionSessionTask` API after the task completes. The total size of the
            return values after JSON serialization must not exceed 4 MB. If the limit is
            exceeded, the task terminates with an error.

            If the script raises an unhandled error, the task terminates. The error
            information can be retrieved with the `GetLuauExecutionSessionTask` API.

            Standard output (generated by the Luau `print` function) can be retrieved
            with the `ListLuauExecutionSessionTaskLogs` method after the task completes.
            A maximum of 450 KB of logs are retained. If the amount of logs exceeds the
            limit, older logs are discarded.

            Information about a task is retained for 24 hours after task completion.

            At most ten incomplete tasks are allowed per place. Attempting to create more
            tasks while the first ten are incomplete results in a HTTP 429 response.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[LuauExecutionSessionTask]
    """

    kwargs = _get_kwargs(
        universe_id=universe_id,
        place_id=place_id,
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    universe_id: str,
    place_id: str,
    *,
    client: AuthenticatedClient,
    body: LuauExecutionSessionTask,
) -> LuauExecutionSessionTask | None:
    """Create Luau Execution Session Task

     Creates a task but does not wait for the task to complete.

    To check whether a task has
    completed, call the `GetLuauExecutionSessionTask` method and inspect the
    `state` field of the returned resource.

    Quotas:
    * 5 calls per minute per API key owner
    * 45 calls per minute per IP address

    Args:
        universe_id (str):
        place_id (str):
        body (LuauExecutionSessionTask): A `LuauExecutionSessionTask` ("task" for short) executes
            a given Luau script
            in the context of a specific version of a place.

            In a task, physics simulation does not run. Server and local scripts within
            the place also do not automatically run.

            The script may access and update the data model of the place, including
            invoking any module scripts. However, data model changes are local to the
            task and cannot be persisted.

            The script can also invoke engine APIs that read and/or modify data stored in
            the cloud, such as those for DataStores. Exercise caution when using these
            APIs.

            Scripts can be up to 4 MB in size and run for up to 5 minutes. Scripts that
            run for longer than the time limit terminate with an error.

            Scripts are executed as-is and do not need to be wrapped in a function.

            Scripts can return values (using the Luau `return` keyword). Return values
            are serialized to JSON and can be retrieved with the `Get
            LuauExecutionSessionTask` API after the task completes. The total size of the
            return values after JSON serialization must not exceed 4 MB. If the limit is
            exceeded, the task terminates with an error.

            If the script raises an unhandled error, the task terminates. The error
            information can be retrieved with the `GetLuauExecutionSessionTask` API.

            Standard output (generated by the Luau `print` function) can be retrieved
            with the `ListLuauExecutionSessionTaskLogs` method after the task completes.
            A maximum of 450 KB of logs are retained. If the amount of logs exceeds the
            limit, older logs are discarded.

            Information about a task is retained for 24 hours after task completion.

            At most ten incomplete tasks are allowed per place. Attempting to create more
            tasks while the first ten are incomplete results in a HTTP 429 response.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        LuauExecutionSessionTask
    """

    return (
        await asyncio_detailed(
            universe_id=universe_id,
            place_id=place_id,
            client=client,
            body=body,
        )
    ).parsed
