from enum import Enum


class GetV1AssetsThumbnailsApiReturnPolicy(str, Enum):
    AUTOGENERATED = "AutoGenerated"
    FORCEAUTOGENERATED = "ForceAutoGenerated"
    FORCEPLACEHOLDER = "ForcePlaceHolder"
    PLACEHOLDER = "PlaceHolder"

    def __str__(self) -> str:
        return str(self.value)
