from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.luau_execution_session_task_log_log_message import LuauExecutionSessionTaskLogLogMessage


T = TypeVar("T", bound="LuauExecutionSessionTaskLog")


@_attrs_define
class LuauExecutionSessionTaskLog:
    """Represents a chunk of log messages generated by a
    `LuauExecutionSessionTask`.

    The amount of logs that is retained is limited. See the documentation of the
    `LuauExecutionSessionTask` resource for more details.

    Logs have the same retention time as the parent task.

        Attributes:
            path (str | Unset): The resource path of the luau execution session task log.

                Formats:
                * `universes/{universe_id}/places/{place_id}/luau-execution-session-
                tasks/{luau_execution_session_task_id}/logs/{luau_execution_session_task_log_id}`
                * `universes/{universe_id}/places/{place_id}/versions/{place_version_id}/luau-execution-session-
                tasks/{luau_execution_session_task_id}/logs/{luau_execution_session_task_log_id}`
                * `universes/{universe_id}/places/{place_id}/luau-execution-sessions/{luau_execution_session_id}/tasks/{luau_exe
                cution_session_task_id}/logs/{luau_execution_session_task_log_id}`
                * `universes/{universe_id}/places/{place_id}/versions/{place_version_id}/luau-execution-sessions/{luau_execution
                _session_id}/tasks/{luau_execution_session_task_id}/logs/{luau_execution_session_task_log_id}` Example:
                universes/123/places/123/luau-execution-session-tasks/123e4567-e89b-12d3-a456-426655440000/logs/123.
            messages (list[str] | Unset): A list of log messages generated by the task execution.
                Each call to the Luau `print()` function from the task's script's code
                results in a single list item here, even if the message itself contains
                newlines. This field is populated when the View is FLAT (which is the
                default).
            structured_messages (list[LuauExecutionSessionTaskLogLogMessage] | Unset): A list of log messages generated by
                the task execution and associated
                metadata.
                Each call to the Luau `print()` function from the task's script's code
                results in a single list item here, even if the message itself contains
                newlines. This field is populated when the View is STRUCTURED.
    """

    path: str | Unset = UNSET
    messages: list[str] | Unset = UNSET
    structured_messages: list[LuauExecutionSessionTaskLogLogMessage] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        path = self.path

        messages: list[str] | Unset = UNSET
        if not isinstance(self.messages, Unset):
            messages = self.messages

        structured_messages: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.structured_messages, Unset):
            structured_messages = []
            for structured_messages_item_data in self.structured_messages:
                structured_messages_item = structured_messages_item_data.to_dict()
                structured_messages.append(structured_messages_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if path is not UNSET:
            field_dict["path"] = path
        if messages is not UNSET:
            field_dict["messages"] = messages
        if structured_messages is not UNSET:
            field_dict["structuredMessages"] = structured_messages

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.luau_execution_session_task_log_log_message import LuauExecutionSessionTaskLogLogMessage

        d = dict(src_dict)
        path = d.pop("path", UNSET)

        messages = cast(list[str], d.pop("messages", UNSET))

        _structured_messages = d.pop("structuredMessages", UNSET)
        structured_messages: list[LuauExecutionSessionTaskLogLogMessage] | Unset = UNSET
        if _structured_messages is not UNSET:
            structured_messages = []
            for structured_messages_item_data in _structured_messages:
                structured_messages_item = LuauExecutionSessionTaskLogLogMessage.from_dict(
                    structured_messages_item_data
                )

                structured_messages.append(structured_messages_item)

        luau_execution_session_task_log = cls(
            path=path,
            messages=messages,
            structured_messages=structured_messages,
        )

        luau_execution_session_task_log.additional_properties = d
        return luau_execution_session_task_log

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
