from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.luau_execution_session_task_state import LuauExecutionSessionTaskState
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.luau_execution_session_task_error import LuauExecutionSessionTaskError
    from ..models.luau_execution_session_task_output import LuauExecutionSessionTaskOutput


T = TypeVar("T", bound="LuauExecutionSessionTask")


@_attrs_define
class LuauExecutionSessionTask:
    """A `LuauExecutionSessionTask` ("task" for short) executes a given Luau script
    in the context of a specific version of a place.

    In a task, physics simulation does not run. Server and local scripts within
    the place also do not automatically run.

    The script may access and update the data model of the place, including
    invoking any module scripts. However, data model changes are local to the
    task and cannot be persisted.

    The script can also invoke engine APIs that read and/or modify data stored in
    the cloud, such as those for DataStores. Exercise caution when using these
    APIs.

    Scripts can be up to 4 MB in size and run for up to 5 minutes. Scripts that
    run for longer than the time limit terminate with an error.

    Scripts are executed as-is and do not need to be wrapped in a function.

    Scripts can return values (using the Luau `return` keyword). Return values
    are serialized to JSON and can be retrieved with the `Get
    LuauExecutionSessionTask` API after the task completes. The total size of the
    return values after JSON serialization must not exceed 4 MB. If the limit is
    exceeded, the task terminates with an error.

    If the script raises an unhandled error, the task terminates. The error
    information can be retrieved with the `GetLuauExecutionSessionTask` API.

    Standard output (generated by the Luau `print` function) can be retrieved
    with the `ListLuauExecutionSessionTaskLogs` method after the task completes.
    A maximum of 450 KB of logs are retained. If the amount of logs exceeds the
    limit, older logs are discarded.

    Information about a task is retained for 24 hours after task completion.

    At most ten incomplete tasks are allowed per place. Attempting to create more
    tasks while the first ten are incomplete results in a HTTP 429 response.

        Attributes:
            path (str | Unset): The resource path of the luau execution session task.

                Formats:
                * `universes/{universe_id}/places/{place_id}/luau-execution-session-tasks/{luau_execution_session_task_id}`
                * `universes/{universe_id}/places/{place_id}/versions/{place_version_id}/luau-execution-session-
                tasks/{luau_execution_session_task_id}`
                * `universes/{universe_id}/places/{place_id}/luau-execution-
                sessions/{luau_execution_session_id}/tasks/{luau_execution_session_task_id}`
                * `universes/{universe_id}/places/{place_id}/versions/{place_version_id}/luau-execution-
                sessions/{luau_execution_session_id}/tasks/{luau_execution_session_task_id}` Example:
                universes/123/places/123/luau-execution-session-tasks/123e4567-e89b-12d3-a456-426655440000.
            create_time (datetime.datetime | Unset): Time when this task was created. Example: 2023-07-05T12:34:56Z.
            update_time (datetime.datetime | Unset): Time when this task's state last changed. Example:
                2023-07-05T12:34:56Z.
            user (str | Unset): The user that created the API key that was used to create this task.
            state (LuauExecutionSessionTaskState | Unset): The task's state. See the State enum for information about each
                possible
                value.

                Possible values:

                  | Value | Description |
                  | --- | --- |
                  | STATE_UNSPECIFIED | UNSPECIFIED |
                  | QUEUED | The Task is waiting to be processed. |
                  | PROCESSING | The Task has been picked up for processing. |
                  | CANCELLED | The Task has been stopped by the user. |
                  | COMPLETE | The Task has finished processing. The output field contains the output. |
                  | FAILED | The Task failed. The error field contains details about the error. | Example: STATE_UNSPECIFIED.
            script (str | Unset): The script to be run as part of this task.

                For example:

                ```luau
                local x = 3
                local y = 4
                return x + y
                ```
            timeout (str | Unset): Limit for how long the script can run.

                The task fails if the script does not complete within the
                specified duration.

                Defaults to 5 minutes. Example: 3s.
            error (LuauExecutionSessionTaskError | Unset): Contains error details in case of failed execution.
            output (LuauExecutionSessionTaskOutput | Unset): Contains the output of a task's execution.
            binary_input (str | Unset): Resource path of the binary input to this task. See the documentation for
                the
                `LuauExecutionSessionTaskBinaryInput` resource for usage details.
            enable_binary_output (bool | Unset): If set to true, allows the task to output a large binary object in addition
                to standard return values.

                If `enable_binary_output` is set to true, the task script must return a
                `LuauExecutionTaskOutput` (or equivalent table) and no other return values.

                Below is example code for doing so:

                ```luau
                local buf: buffer = buffer.create(10)
                local result: LuauExecutionTaskOutput = {
                  BinaryOutput = buf,
                  ReturnValues = { "hello world", 123 }
                }
                return result
                ```

                The `BinaryOutput` buffer must be no larger than 256 MiB in size.

                The `ReturnValues` array, if given, will be serialized to JSON and made
                available in the `output` field of the `LuauExecutionSessionTask` resource,
                similar to regular return values when not using `enable_binary_output`.

                The binary output can be fetched from the URI in the `binaryOutputUri`
                field after the task completes. The `binaryOutputUri` is valid for 15
                minutes after task completion. Example: True.
            binary_output_uri (str | Unset): URI for the binary output of this task. See the `enableBinaryOutput` field
                for usage details.
    """

    path: str | Unset = UNSET
    create_time: datetime.datetime | Unset = UNSET
    update_time: datetime.datetime | Unset = UNSET
    user: str | Unset = UNSET
    state: LuauExecutionSessionTaskState | Unset = UNSET
    script: str | Unset = UNSET
    timeout: str | Unset = UNSET
    error: LuauExecutionSessionTaskError | Unset = UNSET
    output: LuauExecutionSessionTaskOutput | Unset = UNSET
    binary_input: str | Unset = UNSET
    enable_binary_output: bool | Unset = UNSET
    binary_output_uri: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        path = self.path

        create_time: str | Unset = UNSET
        if not isinstance(self.create_time, Unset):
            create_time = self.create_time.isoformat()

        update_time: str | Unset = UNSET
        if not isinstance(self.update_time, Unset):
            update_time = self.update_time.isoformat()

        user = self.user

        state: str | Unset = UNSET
        if not isinstance(self.state, Unset):
            state = self.state.value

        script = self.script

        timeout = self.timeout

        error: dict[str, Any] | Unset = UNSET
        if not isinstance(self.error, Unset):
            error = self.error.to_dict()

        output: dict[str, Any] | Unset = UNSET
        if not isinstance(self.output, Unset):
            output = self.output.to_dict()

        binary_input = self.binary_input

        enable_binary_output = self.enable_binary_output

        binary_output_uri = self.binary_output_uri

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if path is not UNSET:
            field_dict["path"] = path
        if create_time is not UNSET:
            field_dict["createTime"] = create_time
        if update_time is not UNSET:
            field_dict["updateTime"] = update_time
        if user is not UNSET:
            field_dict["user"] = user
        if state is not UNSET:
            field_dict["state"] = state
        if script is not UNSET:
            field_dict["script"] = script
        if timeout is not UNSET:
            field_dict["timeout"] = timeout
        if error is not UNSET:
            field_dict["error"] = error
        if output is not UNSET:
            field_dict["output"] = output
        if binary_input is not UNSET:
            field_dict["binaryInput"] = binary_input
        if enable_binary_output is not UNSET:
            field_dict["enableBinaryOutput"] = enable_binary_output
        if binary_output_uri is not UNSET:
            field_dict["binaryOutputUri"] = binary_output_uri

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.luau_execution_session_task_error import LuauExecutionSessionTaskError
        from ..models.luau_execution_session_task_output import LuauExecutionSessionTaskOutput

        d = dict(src_dict) if isinstance(src_dict, Mapping) else {}
        path = d.pop("path", UNSET)

        _create_time = d.pop("createTime", UNSET)
        create_time: datetime.datetime | Unset
        if isinstance(_create_time, Unset):
            create_time = UNSET
        else:
            create_time = datetime.datetime.fromisoformat(_create_time)

        _update_time = d.pop("updateTime", UNSET)
        update_time: datetime.datetime | Unset
        if isinstance(_update_time, Unset):
            update_time = UNSET
        else:
            update_time = datetime.datetime.fromisoformat(_update_time)

        user = d.pop("user", UNSET)

        _state = d.pop("state", UNSET)
        state: LuauExecutionSessionTaskState | Unset
        if isinstance(_state, Unset):
            state = UNSET
        else:
            state = LuauExecutionSessionTaskState(_state)

        script = d.pop("script", UNSET)

        timeout = d.pop("timeout", UNSET)

        _error = d.pop("error", UNSET)
        error: LuauExecutionSessionTaskError | Unset
        if isinstance(_error, Unset):
            error = UNSET
        else:
            error = LuauExecutionSessionTaskError.from_dict(_error)

        _output = d.pop("output", UNSET)
        output: LuauExecutionSessionTaskOutput | Unset
        if isinstance(_output, Unset):
            output = UNSET
        else:
            output = LuauExecutionSessionTaskOutput.from_dict(_output)

        binary_input = d.pop("binaryInput", UNSET)

        enable_binary_output = d.pop("enableBinaryOutput", UNSET)

        binary_output_uri = d.pop("binaryOutputUri", UNSET)

        luau_execution_session_task = cls(
            path=path,
            create_time=create_time,
            update_time=update_time,
            user=user,
            state=state,
            script=script,
            timeout=timeout,
            error=error,
            output=output,
            binary_input=binary_input,
            enable_binary_output=enable_binary_output,
            binary_output_uri=binary_output_uri,
        )

        luau_execution_session_task.additional_properties = d
        return luau_execution_session_task

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
