from enum import Enum


class OperationalStatus(str, Enum):
    CREATING = "OPERATIONAL_STATUS_CREATING"
    DELETING = "OPERATIONAL_STATUS_DELETING"
    RAMPING_UP = "OPERATIONAL_STATUS_RAMPING_UP"
    READY = "OPERATIONAL_STATUS_READY"
    ROLLING_OUT = "OPERATIONAL_STATUS_ROLLING_OUT"
    SCHEDULING = "OPERATIONAL_STATUS_SCHEDULING"
    STARTING = "OPERATIONAL_STATUS_STARTING"
    STOPPING = "OPERATIONAL_STATUS_STOPPING"
    SYNCING = "OPERATIONAL_STATUS_SYNCING"
    UPDATING = "OPERATIONAL_STATUS_UPDATING"

    def __str__(self) -> str:
        return str(self.value)
