from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

from ..models.roblox_ad_configuration_api_sponsored_game_v2_model_ad_set_status import (
    RobloxAdConfigurationApiSponsoredGameV2ModelAdSetStatus,
)
from ..models.roblox_ad_configuration_api_sponsored_game_v2_model_ad_status import (
    RobloxAdConfigurationApiSponsoredGameV2ModelAdStatus,
)
from ..models.roblox_ad_configuration_api_sponsored_game_v2_model_campaign_target_type import (
    RobloxAdConfigurationApiSponsoredGameV2ModelCampaignTargetType,
)
from ..models.roblox_ad_configuration_api_sponsored_game_v2_model_creative_type import (
    RobloxAdConfigurationApiSponsoredGameV2ModelCreativeType,
)
from ..models.roblox_ad_configuration_api_sponsored_game_v2_model_target_age_bracket import (
    RobloxAdConfigurationApiSponsoredGameV2ModelTargetAgeBracket,
)
from ..models.roblox_ad_configuration_api_sponsored_game_v2_model_target_device_type import (
    RobloxAdConfigurationApiSponsoredGameV2ModelTargetDeviceType,
)
from ..models.roblox_ad_configuration_api_sponsored_game_v2_model_target_gender import (
    RobloxAdConfigurationApiSponsoredGameV2ModelTargetGender,
)
from ..types import UNSET, Unset

T = TypeVar("T", bound="RobloxAdConfigurationApiSponsoredGameV2Model")


@_attrs_define
class RobloxAdConfigurationApiSponsoredGameV2Model:
    """A response model represents an Ad with complete information, including infos from its associated campaign and ad set

    Attributes:
        ad_id (int | Unset): The id of the ad
        ad_set_id (int | Unset): The id of the ad set
        ad_name (str | Unset): The name of the Ad
        ad_status (RobloxAdConfigurationApiSponsoredGameV2ModelAdStatus | Unset): The status of the ad ['Undefined' = 0,
            'Draft' = 1, 'PendingApproval' = 2, 'Approved' = 3, 'Moderated' = 4]
        creative_type (RobloxAdConfigurationApiSponsoredGameV2ModelCreativeType | Unset): The type of the creative
            associated with the Ad ['Undefined' = 0, 'Image' = 1, 'Video' = 2]
        creative_target_id (int | Unset): The target id of the creative associated with the Ad
        creative_url (str | Unset): The Url of the creative
        bid_amount_in_robux (int | Unset): The bid amount of the Ad in Robux
        budget_in_robux (int | Unset): The budget of the ad set in Robux
        ad_set_status (RobloxAdConfigurationApiSponsoredGameV2ModelAdSetStatus | Unset): The status of the ad set
            ['Undefined' = 0, 'Draft' = 1, 'Scheduled' = 2, 'Running' = 3, 'Paused' = 4, 'Stopped' = 5, 'Completed' = 6]
        start_date (datetime.datetime | Unset): The start date of the ad set
        end_date (datetime.datetime | Unset): The end date of the ad set
        target_gender (RobloxAdConfigurationApiSponsoredGameV2ModelTargetGender | Unset): The target gender of the ad
            set ['Undefined' = 1, 'Male' = 2, 'Female' = 4]
        target_age_bracket (RobloxAdConfigurationApiSponsoredGameV2ModelTargetAgeBracket | Unset): The target age
            bracket of the ad set ['Undefined' = 1, 'AgeUnder13' = 2, 'Age13OrOver' = 4, 'Age13To16' = 8, 'Age17OrOver' =
            16]
        target_device_type (RobloxAdConfigurationApiSponsoredGameV2ModelTargetDeviceType | Unset): The target device
            type of the ad set ['Undefined' = 1, 'Computer' = 2, 'Phone' = 4, 'Tablet' = 8, 'Console' = 16, 'VR' = 32]
        campaign_target_type (RobloxAdConfigurationApiSponsoredGameV2ModelCampaignTargetType | Unset): The target type
            of the campaign ['Undefined' = 0, 'Universe' = 1, 'Asset' = 2, 'ImmersiveAd' = 3]
        campaign_target_id (int | Unset): The target id of the campaign
        total_spend_in_robux (int | Unset): The total spend of the ad set in Robux
        total_impressions (int | Unset): The total number of impressions generated by the ad
        total_clicks (int | Unset): The total number of clicks generated by the ad
        total_conversions (int | Unset): The total number of conversions generated by the ad
        impression_conversions (int | Unset): The number of conversions by ad impression generated by the ad
        click_conversions (int | Unset): The number of conversions by ad click generated by the ad
    """

    ad_id: int | Unset = UNSET
    ad_set_id: int | Unset = UNSET
    ad_name: str | Unset = UNSET
    ad_status: RobloxAdConfigurationApiSponsoredGameV2ModelAdStatus | Unset = UNSET
    creative_type: RobloxAdConfigurationApiSponsoredGameV2ModelCreativeType | Unset = UNSET
    creative_target_id: int | Unset = UNSET
    creative_url: str | Unset = UNSET
    bid_amount_in_robux: int | Unset = UNSET
    budget_in_robux: int | Unset = UNSET
    ad_set_status: RobloxAdConfigurationApiSponsoredGameV2ModelAdSetStatus | Unset = UNSET
    start_date: datetime.datetime | Unset = UNSET
    end_date: datetime.datetime | Unset = UNSET
    target_gender: RobloxAdConfigurationApiSponsoredGameV2ModelTargetGender | Unset = UNSET
    target_age_bracket: RobloxAdConfigurationApiSponsoredGameV2ModelTargetAgeBracket | Unset = UNSET
    target_device_type: RobloxAdConfigurationApiSponsoredGameV2ModelTargetDeviceType | Unset = UNSET
    campaign_target_type: RobloxAdConfigurationApiSponsoredGameV2ModelCampaignTargetType | Unset = UNSET
    campaign_target_id: int | Unset = UNSET
    total_spend_in_robux: int | Unset = UNSET
    total_impressions: int | Unset = UNSET
    total_clicks: int | Unset = UNSET
    total_conversions: int | Unset = UNSET
    impression_conversions: int | Unset = UNSET
    click_conversions: int | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        ad_id = self.ad_id

        ad_set_id = self.ad_set_id

        ad_name = self.ad_name

        ad_status: int | Unset = UNSET
        if not isinstance(self.ad_status, Unset):
            ad_status = self.ad_status.value

        creative_type: int | Unset = UNSET
        if not isinstance(self.creative_type, Unset):
            creative_type = self.creative_type.value

        creative_target_id = self.creative_target_id

        creative_url = self.creative_url

        bid_amount_in_robux = self.bid_amount_in_robux

        budget_in_robux = self.budget_in_robux

        ad_set_status: int | Unset = UNSET
        if not isinstance(self.ad_set_status, Unset):
            ad_set_status = self.ad_set_status.value

        start_date: str | Unset = UNSET
        if not isinstance(self.start_date, Unset):
            start_date = self.start_date.isoformat()

        end_date: str | Unset = UNSET
        if not isinstance(self.end_date, Unset):
            end_date = self.end_date.isoformat()

        target_gender: int | Unset = UNSET
        if not isinstance(self.target_gender, Unset):
            target_gender = self.target_gender.value

        target_age_bracket: int | Unset = UNSET
        if not isinstance(self.target_age_bracket, Unset):
            target_age_bracket = self.target_age_bracket.value

        target_device_type: int | Unset = UNSET
        if not isinstance(self.target_device_type, Unset):
            target_device_type = self.target_device_type.value

        campaign_target_type: int | Unset = UNSET
        if not isinstance(self.campaign_target_type, Unset):
            campaign_target_type = self.campaign_target_type.value

        campaign_target_id = self.campaign_target_id

        total_spend_in_robux = self.total_spend_in_robux

        total_impressions = self.total_impressions

        total_clicks = self.total_clicks

        total_conversions = self.total_conversions

        impression_conversions = self.impression_conversions

        click_conversions = self.click_conversions

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if ad_id is not UNSET:
            field_dict["adId"] = ad_id
        if ad_set_id is not UNSET:
            field_dict["adSetId"] = ad_set_id
        if ad_name is not UNSET:
            field_dict["adName"] = ad_name
        if ad_status is not UNSET:
            field_dict["adStatus"] = ad_status
        if creative_type is not UNSET:
            field_dict["creativeType"] = creative_type
        if creative_target_id is not UNSET:
            field_dict["creativeTargetId"] = creative_target_id
        if creative_url is not UNSET:
            field_dict["creativeUrl"] = creative_url
        if bid_amount_in_robux is not UNSET:
            field_dict["bidAmountInRobux"] = bid_amount_in_robux
        if budget_in_robux is not UNSET:
            field_dict["budgetInRobux"] = budget_in_robux
        if ad_set_status is not UNSET:
            field_dict["adSetStatus"] = ad_set_status
        if start_date is not UNSET:
            field_dict["startDate"] = start_date
        if end_date is not UNSET:
            field_dict["endDate"] = end_date
        if target_gender is not UNSET:
            field_dict["targetGender"] = target_gender
        if target_age_bracket is not UNSET:
            field_dict["targetAgeBracket"] = target_age_bracket
        if target_device_type is not UNSET:
            field_dict["targetDeviceType"] = target_device_type
        if campaign_target_type is not UNSET:
            field_dict["campaignTargetType"] = campaign_target_type
        if campaign_target_id is not UNSET:
            field_dict["campaignTargetId"] = campaign_target_id
        if total_spend_in_robux is not UNSET:
            field_dict["totalSpendInRobux"] = total_spend_in_robux
        if total_impressions is not UNSET:
            field_dict["totalImpressions"] = total_impressions
        if total_clicks is not UNSET:
            field_dict["totalClicks"] = total_clicks
        if total_conversions is not UNSET:
            field_dict["totalConversions"] = total_conversions
        if impression_conversions is not UNSET:
            field_dict["impressionConversions"] = impression_conversions
        if click_conversions is not UNSET:
            field_dict["clickConversions"] = click_conversions

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        ad_id = d.pop("adId", UNSET)

        ad_set_id = d.pop("adSetId", UNSET)

        ad_name = d.pop("adName", UNSET)

        _ad_status = d.pop("adStatus", UNSET)
        ad_status: RobloxAdConfigurationApiSponsoredGameV2ModelAdStatus | Unset
        if isinstance(_ad_status, Unset):
            ad_status = UNSET
        else:
            ad_status = RobloxAdConfigurationApiSponsoredGameV2ModelAdStatus(_ad_status)

        _creative_type = d.pop("creativeType", UNSET)
        creative_type: RobloxAdConfigurationApiSponsoredGameV2ModelCreativeType | Unset
        if isinstance(_creative_type, Unset):
            creative_type = UNSET
        else:
            creative_type = RobloxAdConfigurationApiSponsoredGameV2ModelCreativeType(_creative_type)

        creative_target_id = d.pop("creativeTargetId", UNSET)

        creative_url = d.pop("creativeUrl", UNSET)

        bid_amount_in_robux = d.pop("bidAmountInRobux", UNSET)

        budget_in_robux = d.pop("budgetInRobux", UNSET)

        _ad_set_status = d.pop("adSetStatus", UNSET)
        ad_set_status: RobloxAdConfigurationApiSponsoredGameV2ModelAdSetStatus | Unset
        if isinstance(_ad_set_status, Unset):
            ad_set_status = UNSET
        else:
            ad_set_status = RobloxAdConfigurationApiSponsoredGameV2ModelAdSetStatus(_ad_set_status)

        _start_date = d.pop("startDate", UNSET)
        start_date: datetime.datetime | Unset
        if isinstance(_start_date, Unset):
            start_date = UNSET
        else:
            start_date = datetime.datetime.fromisoformat(_start_date)

        _end_date = d.pop("endDate", UNSET)
        end_date: datetime.datetime | Unset
        if isinstance(_end_date, Unset):
            end_date = UNSET
        else:
            end_date = datetime.datetime.fromisoformat(_end_date)

        _target_gender = d.pop("targetGender", UNSET)
        target_gender: RobloxAdConfigurationApiSponsoredGameV2ModelTargetGender | Unset
        if isinstance(_target_gender, Unset):
            target_gender = UNSET
        else:
            target_gender = RobloxAdConfigurationApiSponsoredGameV2ModelTargetGender(_target_gender)

        _target_age_bracket = d.pop("targetAgeBracket", UNSET)
        target_age_bracket: RobloxAdConfigurationApiSponsoredGameV2ModelTargetAgeBracket | Unset
        if isinstance(_target_age_bracket, Unset):
            target_age_bracket = UNSET
        else:
            target_age_bracket = RobloxAdConfigurationApiSponsoredGameV2ModelTargetAgeBracket(_target_age_bracket)

        _target_device_type = d.pop("targetDeviceType", UNSET)
        target_device_type: RobloxAdConfigurationApiSponsoredGameV2ModelTargetDeviceType | Unset
        if isinstance(_target_device_type, Unset):
            target_device_type = UNSET
        else:
            target_device_type = RobloxAdConfigurationApiSponsoredGameV2ModelTargetDeviceType(_target_device_type)

        _campaign_target_type = d.pop("campaignTargetType", UNSET)
        campaign_target_type: RobloxAdConfigurationApiSponsoredGameV2ModelCampaignTargetType | Unset
        if isinstance(_campaign_target_type, Unset):
            campaign_target_type = UNSET
        else:
            campaign_target_type = RobloxAdConfigurationApiSponsoredGameV2ModelCampaignTargetType(_campaign_target_type)

        campaign_target_id = d.pop("campaignTargetId", UNSET)

        total_spend_in_robux = d.pop("totalSpendInRobux", UNSET)

        total_impressions = d.pop("totalImpressions", UNSET)

        total_clicks = d.pop("totalClicks", UNSET)

        total_conversions = d.pop("totalConversions", UNSET)

        impression_conversions = d.pop("impressionConversions", UNSET)

        click_conversions = d.pop("clickConversions", UNSET)

        roblox_ad_configuration_api_sponsored_game_v2_model = cls(
            ad_id=ad_id,
            ad_set_id=ad_set_id,
            ad_name=ad_name,
            ad_status=ad_status,
            creative_type=creative_type,
            creative_target_id=creative_target_id,
            creative_url=creative_url,
            bid_amount_in_robux=bid_amount_in_robux,
            budget_in_robux=budget_in_robux,
            ad_set_status=ad_set_status,
            start_date=start_date,
            end_date=end_date,
            target_gender=target_gender,
            target_age_bracket=target_age_bracket,
            target_device_type=target_device_type,
            campaign_target_type=campaign_target_type,
            campaign_target_id=campaign_target_id,
            total_spend_in_robux=total_spend_in_robux,
            total_impressions=total_impressions,
            total_clicks=total_clicks,
            total_conversions=total_conversions,
            impression_conversions=impression_conversions,
            click_conversions=click_conversions,
        )

        return roblox_ad_configuration_api_sponsored_game_v2_model
