from enum import Enum


class RobloxThumbnailsApisModelsThumbnailBatchRequestType(str, Enum):
    ASSET = "Asset"
    AUTOGENERATEDASSET = "AutoGeneratedAsset"
    AUTOGENERATEDGAMEICON = "AutoGeneratedGameIcon"
    AVATAR = "Avatar"
    AVATARBUST = "AvatarBust"
    AVATARHEADSHOT = "AvatarHeadShot"
    BADGEICON = "BadgeIcon"
    BUNDLETHUMBNAIL = "BundleThumbnail"
    CREATORCONTEXTASSET = "CreatorContextAsset"
    DEVELOPERPRODUCT = "DeveloperProduct"
    FORCEAUTOGENERATEDGAMEICON = "ForceAutoGeneratedGameIcon"
    GAMEICON = "GameIcon"
    GAMEPASS = "GamePass"
    GAMETHUMBNAIL = "GameThumbnail"
    GROUPICON = "GroupIcon"
    LOOK = "Look"
    OUTFIT = "Outfit"
    PLACEICON = "PlaceIcon"
    SCREENSHOT = "Screenshot"

    def __str__(self) -> str:
        return str(self.value)
