from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define

from ..models.roblox_thumbnails_apis_models_thumbnail_batch_request_type import (
    RobloxThumbnailsApisModelsThumbnailBatchRequestType,
)
from ..types import UNSET, Unset

T = TypeVar("T", bound="RobloxThumbnailsApisModelsThumbnailBatchRequest")


@_attrs_define
class RobloxThumbnailsApisModelsThumbnailBatchRequest:
    """
    Attributes:
        request_id (str | Unset): The request id. (Generated client side, used to represent the items in the request)
        target_id (int | Unset): The thumbnail target id
        token (str | Unset): Alternative ase token used to identify a thumbnail
        alias (str | Unset): Alternative string used to identify a thumbnail
            instead of targetId
        type_ (RobloxThumbnailsApisModelsThumbnailBatchRequestType | Unset): The type of the thumbnails ['Avatar' = 1,
            'AvatarHeadShot' = 2, 'GameIcon' = 3, 'BadgeIcon' = 4, 'GameThumbnail' = 5, 'GamePass' = 6, 'Asset' = 7,
            'BundleThumbnail' = 8, 'Outfit' = 9, 'GroupIcon' = 10, 'DeveloperProduct' = 11, 'AvatarBust' = 12,
            'AutoGeneratedAsset' = 13, 'PlaceIcon' = 14, 'AutoGeneratedGameIcon' = 15, 'ForceAutoGeneratedGameIcon' = 16,
            'Look' = 17, 'CreatorContextAsset' = 18, 'Screenshot' = 19]
        size (str | Unset): The thumbnail size
        format_ (str | Unset): The thumbnail format
        is_circular (bool | Unset): Is the thumbnail circular shape
        access_context (str | Unset): Access context for asset permission checks (only relevant for Asset thumbnail
            types)
        head_shape (str | Unset): Head shape for dynamic head thumbnails (only relevant for Asset thumbnail types with
            dynamic head)
        include_background (bool | Unset): Whether to include a background in avatar thumbnails (defaults to false)
    """

    request_id: str | Unset = UNSET
    target_id: int | Unset = UNSET
    token: str | Unset = UNSET
    alias: str | Unset = UNSET
    type_: RobloxThumbnailsApisModelsThumbnailBatchRequestType | Unset = UNSET
    size: str | Unset = UNSET
    format_: str | Unset = UNSET
    is_circular: bool | Unset = UNSET
    access_context: str | Unset = UNSET
    head_shape: str | Unset = UNSET
    include_background: bool | Unset = UNSET

    def to_dict(self) -> dict[str, Any]:
        request_id = self.request_id

        target_id = self.target_id

        token = self.token

        alias = self.alias

        type_: str | Unset = UNSET
        if not isinstance(self.type_, Unset):
            type_ = self.type_.value

        size = self.size

        format_ = self.format_

        is_circular = self.is_circular

        access_context = self.access_context

        head_shape = self.head_shape

        include_background = self.include_background

        field_dict: dict[str, Any] = {}

        field_dict.update({})
        if request_id is not UNSET:
            field_dict["requestId"] = request_id
        if target_id is not UNSET:
            field_dict["targetId"] = target_id
        if token is not UNSET:
            field_dict["token"] = token
        if alias is not UNSET:
            field_dict["alias"] = alias
        if type_ is not UNSET:
            field_dict["type"] = type_
        if size is not UNSET:
            field_dict["size"] = size
        if format_ is not UNSET:
            field_dict["format"] = format_
        if is_circular is not UNSET:
            field_dict["isCircular"] = is_circular
        if access_context is not UNSET:
            field_dict["accessContext"] = access_context
        if head_shape is not UNSET:
            field_dict["headShape"] = head_shape
        if include_background is not UNSET:
            field_dict["includeBackground"] = include_background

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict) if isinstance(src_dict, Mapping) else {}
        request_id = d.pop("requestId", UNSET)

        target_id = d.pop("targetId", UNSET)

        token = d.pop("token", UNSET)

        alias = d.pop("alias", UNSET)

        _type_ = d.pop("type", UNSET)
        type_: RobloxThumbnailsApisModelsThumbnailBatchRequestType | Unset
        if isinstance(_type_, Unset):
            type_ = UNSET
        else:
            type_ = RobloxThumbnailsApisModelsThumbnailBatchRequestType(_type_)

        size = d.pop("size", UNSET)

        format_ = d.pop("format", UNSET)

        is_circular = d.pop("isCircular", UNSET)

        access_context = d.pop("accessContext", UNSET)

        head_shape = d.pop("headShape", UNSET)

        include_background = d.pop("includeBackground", UNSET)

        roblox_thumbnails_apis_models_thumbnail_batch_request = cls(
            request_id=request_id,
            target_id=target_id,
            token=token,
            alias=alias,
            type_=type_,
            size=size,
            format_=format_,
            is_circular=is_circular,
            access_context=access_context,
            head_shape=head_shape,
            include_background=include_background,
        )

        return roblox_thumbnails_apis_models_thumbnail_batch_request
