from enum import Enum


class TransactionRecordsApiHttpStatusCode(str, Enum):
    ACCEPTED = "Accepted"
    ALREADYREPORTED = "AlreadyReported"
    BADGATEWAY = "BadGateway"
    BADREQUEST = "BadRequest"
    CONFLICT = "Conflict"
    CONTINUE = "Continue"
    CREATED = "Created"
    EARLYHINTS = "EarlyHints"
    EXPECTATIONFAILED = "ExpectationFailed"
    FAILEDDEPENDENCY = "FailedDependency"
    FORBIDDEN = "Forbidden"
    FOUND = "Found"
    GATEWAYTIMEOUT = "GatewayTimeout"
    GONE = "Gone"
    HTTPVERSIONNOTSUPPORTED = "HttpVersionNotSupported"
    IMUSED = "IMUsed"
    INSUFFICIENTSTORAGE = "InsufficientStorage"
    INTERNALSERVERERROR = "InternalServerError"
    LENGTHREQUIRED = "LengthRequired"
    LOCKED = "Locked"
    LOOPDETECTED = "LoopDetected"
    METHODNOTALLOWED = "MethodNotAllowed"
    MISDIRECTEDREQUEST = "MisdirectedRequest"
    MOVEDPERMANENTLY = "MovedPermanently"
    MULTIPLECHOICES = "MultipleChoices"
    MULTISTATUS = "MultiStatus"
    NETWORKAUTHENTICATIONREQUIRED = "NetworkAuthenticationRequired"
    NOCONTENT = "NoContent"
    NONAUTHORITATIVEINFORMATION = "NonAuthoritativeInformation"
    NOTACCEPTABLE = "NotAcceptable"
    NOTEXTENDED = "NotExtended"
    NOTFOUND = "NotFound"
    NOTIMPLEMENTED = "NotImplemented"
    NOTMODIFIED = "NotModified"
    OK = "OK"
    PARTIALCONTENT = "PartialContent"
    PAYMENTREQUIRED = "PaymentRequired"
    PERMANENTREDIRECT = "PermanentRedirect"
    PRECONDITIONFAILED = "PreconditionFailed"
    PRECONDITIONREQUIRED = "PreconditionRequired"
    PROCESSING = "Processing"
    PROXYAUTHENTICATIONREQUIRED = "ProxyAuthenticationRequired"
    REDIRECTKEEPVERB = "RedirectKeepVerb"
    REQUESTEDRANGENOTSATISFIABLE = "RequestedRangeNotSatisfiable"
    REQUESTENTITYTOOLARGE = "RequestEntityTooLarge"
    REQUESTHEADERFIELDSTOOLARGE = "RequestHeaderFieldsTooLarge"
    REQUESTTIMEOUT = "RequestTimeout"
    REQUESTURITOOLONG = "RequestUriTooLong"
    RESETCONTENT = "ResetContent"
    SEEOTHER = "SeeOther"
    SERVICEUNAVAILABLE = "ServiceUnavailable"
    SWITCHINGPROTOCOLS = "SwitchingProtocols"
    TOOMANYREQUESTS = "TooManyRequests"
    UNAUTHORIZED = "Unauthorized"
    UNAVAILABLEFORLEGALREASONS = "UnavailableForLegalReasons"
    UNPROCESSABLEENTITY = "UnprocessableEntity"
    UNSUPPORTEDMEDIATYPE = "UnsupportedMediaType"
    UNUSED = "Unused"
    UPGRADEREQUIRED = "UpgradeRequired"
    USEPROXY = "UseProxy"
    VARIANTALSONEGOTIATES = "VariantAlsoNegotiates"

    def __str__(self) -> str:
        return str(self.value)
